// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrkJOHDt3N85hXKXFFv0Qp4W7Mh95ecdM',
    appId: '1:1028749051541:web:57767dfebe564bcbb77d9c',
    messagingSenderId: '1028749051541',
    projectId: 'threadly-f68ff',
    authDomain: 'threadly-f68ff.firebaseapp.com',
    storageBucket: 'threadly-f68ff.firebasestorage.app',
    measurementId: 'G-CZCYKB2M7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBhed4gbepIodHsq-AriUeLsbhQUGZoA',
    appId: '1:1028749051541:android:855bf4d38dd6a745b77d9c',
    messagingSenderId: '1028749051541',
    projectId: 'threadly-f68ff',
    storageBucket: 'threadly-f68ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0fqsTjKyjduVNBtozhavIQgJI_zLRAxk',
    appId: '1:1028749051541:ios:e55d8376277d4242b77d9c',
    messagingSenderId: '1028749051541',
    projectId: 'threadly-f68ff',
    storageBucket: 'threadly-f68ff.firebasestorage.app',
    iosBundleId: 'com.example.threadly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0fqsTjKyjduVNBtozhavIQgJI_zLRAxk',
    appId: '1:1028749051541:ios:e55d8376277d4242b77d9c',
    messagingSenderId: '1028749051541',
    projectId: 'threadly-f68ff',
    storageBucket: 'threadly-f68ff.firebasestorage.app',
    iosBundleId: 'com.example.threadly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrkJOHDt3N85hXKXFFv0Qp4W7Mh95ecdM',
    appId: '1:1028749051541:web:2735fd9bb980e8f1b77d9c',
    messagingSenderId: '1028749051541',
    projectId: 'threadly-f68ff',
    authDomain: 'threadly-f68ff.firebaseapp.com',
    storageBucket: 'threadly-f68ff.firebasestorage.app',
    measurementId: 'G-HR7J55PV69',
  );
}
